//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCard
    {
        public int Id { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Image { get; set; }
        public Nullable<int> UserInfoId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
